[BE] 사진 인증 (유저 정보 업데이트) (#117)
woowacourse-teams/2021-cvi pull request #123
Opened 2021-08-03 10:32 UTC by taehee-kim-dev

#117

2021-08-03 12:17 UTC, YounghoonKwon commented on backend/src/main/java/com/backjoongwon/cvi/user/domain/User.java
> +        this.shotVerified = updateUser.isShotVerified();
`this.shotVerified = updateUser.shotVerified;`

2021-08-04 00:58 UTC, thisisyoungbin commented on backend/src/main/java/com/backjoongwon/cvi/user/domain/User.java
> +        }
검증 로직!👍

2021-08-04 00:58 UTC, thisisyoungbin approved these changes

2021-08-04 01:29 UTC, Livenow14 requested changes
리뷰 반영 부탁드립니다.

2021-08-04 01:29 UTC, Livenow14 commented on backend/src/main/java/com/backjoongwon/cvi/user/domain/User.java
>          super(id, createdAt);
LastModified부분 추가 바랍니다

2021-08-04 01:29 UTC, YounghoonKwon approved these changes
LGTM

2021-08-04 01:49 UTC, merged