[BE] 마이페이지 페이징 구현(#127)
woowacourse-teams/2021-cvi pull request #134
Opened 2021-08-04 07:15 UTC by thisisyoungbin

#127

2021-08-04 09:14 UTC, YounghoonKwon commented on backend/src/main/java/com/backjoongwon/cvi/post/application/PostService.java
> +    }
리팩토링이 가능할지는 모르겠는데
한번 생각해주셨으면 좋겠어요~~

2021-08-04 09:16 UTC, YounghoonKwon approved these changes

2021-08-05 01:00 UTC, YounghoonKwon commented on backend/src/test/java/com/backjoongwon/cvi/post/application/PostServiceTest.java
> +        @DisplayName("내가 댓글 단 게시글 페이징 조회 - 성공")
스타일!

2021-08-05 01:00 UTC, Livenow14 requested changes
리뷰 반영 부탁드려요

2021-08-05 01:00 UTC, Livenow14 commented on backend/src/test/java/com/backjoongwon/cvi/user/ui/UserControllerTest.java
> +        Filter filter = Filter.NONE;
Filter filter = 이 부분을 willReturn  위로 올리는게 어떨까요?

2021-08-05 01:28 UTC, YounghoonKwon approved these changes

2021-08-05 01:34 UTC, thisisyoungbin commented on backend/src/main/java/com/backjoongwon/cvi/comment/domain/CommentRepositoryImpl.java
> +                .where(comment.user.id.eq(id), comment.id.lt(lastCommentId))
원래 User를 받고 있어서 구분하기 위해 남겨뒀었는데 리팩토링하면서 신경못썼네요! 수정했습니다~

2021-08-05 01:50 UTC, merged