[BE] Post 프로덕션 코드 리팩터링 (#190)
woowacourse-teams/2021-cvi pull request #203
Opened 2021-08-10 04:39 UTC by thisisyoungbin

#190

2021-08-10 05:13 UTC, taehee-kim-dev requested changes
고생하셨어욘

2021-08-10 05:13 UTC, taehee-kim-dev commented on backend/src/main/java/com/backjoongwon/cvi/comment/application/CommentService.java
> +}
Read를 제외한 함수는 @Transactional 붙여주세요!

2021-08-10 05:13 UTC, taehee-kim-dev commented on backend/src/main/java/com/backjoongwon/cvi/like/application/LikeService.java
> +    }
Read를 제외한 함수는 @Transactional 붙여주세요!

2021-08-10 05:13 UTC, taehee-kim-dev commented on backend/src/main/java/com/backjoongwon/cvi/post/application/PostService.java
>  }
Read를 제외한 함수는 @Transactional 붙여주세요!

2021-08-11 01:15 UTC, YounghoonKwon approved these changes

2021-08-11 01:18 UTC, Livenow14 approved these changes
패키지 구조 변경   🙇🏻‍♂️

2021-08-11 01:18 UTC, Livenow14 commented on backend/src/test/java/com/backjoongwon/cvi/comment/service/CommentServiceTest.java
> +        assertThatThrownBy(() -> commentService.updateComment(post.getId(), 0L, optionalUser, updateRequest))
0L 부분을 상수화 해도 좋을 거 같아요~

2021-08-11 01:47 UTC, merged