[BE] 인수 테스트 작성 RestAssured (#188)
woowacourse-teams/2021-cvi pull request #235
Opened 2021-09-02 03:08 UTC by thisisyoungbin

#188

2021-09-02 03:56 UTC, Livenow14 requested changes
수고하셧습니다..!

2021-09-02 03:56 UTC, Livenow14 commented on backend/src/test/java/com/backjoongwon/cvi/like/LikeAcceptanceTest.java
> +        PostResponse postResponse = createPostResponse.as(PostResponse.class);
given 부분에서는, 게시글_작성_되어있음 이러한 메서드를 생성하는 건 어떨까요?

2021-09-02 03:56 UTC, Livenow14 commented on backend/src/test/java/com/backjoongwon/cvi/like/LikeAcceptanceTest.java
> +        anotherUserResponse = anotherSignupResponse.as(UserResponse.class);
이부분은 회원_가입_되어있음 이렇게 메소드를 생성해도 좋을 것 같아요

2021-09-02 03:56 UTC, Livenow14 commented on backend/src/test/java/com/backjoongwon/cvi/post/PostAcceptanceTest.java
> +        List<String> resultPostContents = response.jsonPath()
1, 2를 상수로 빼보는 건 어떨까요 ?

2021-09-06 04:02 UTC, YounghoonKwon approved these changes
👍

2021-09-06 04:04 UTC, merged