[BE] 인증 사진 업로드 S3 저장 기능 구현
woowacourse-teams/2021-cvi pull request #245
Opened 2021-09-06 16:30 UTC by taehee-kim-dev

#234 

후.. 정말 힘들었어요.. 😢 
몇 가지 이슈가 있어서 공유해요.

## 1. orphanRemoval 이 안먹혀요..
Images, Comments, Likes 안의 Collection에서 엔티티를 제거해도 delete 쿼리가 나가질 않습니다..
근데 신기한건 CommentService에서는 이 방식으로 Comment를 제거하는데 delete 쿼리가 나가요..
더 신기한건 PostService에서 이 방식으로 Image를 제거하면 delete 쿼리가 안나가요......................

PostRepositoryTest.java 는 통과하는 테스트입니다. 이 테스트가 통과되는 것은 orphanRemoval 이 안 먹힌다는 것인데요..
왜 이러는지 모르겠네요.. `@Embeddable` 을 사용하면서 그런건지..

## 2. cascade 옵션으로 인한 delete 안되는 이슈...
Images에서 cascade 옵션을 끄면 
```
imageRepository.delete({Image 엔티티}); 
```
를 할 때 delete 쿼리가 나가는데,
cascade 옵션을 켜놓으면 안나가네요.............

테스트 해 보니 Like나 Comment도 delete 쿼리가 안나가네요..

그래서 일단 Images 에서 orphanRemoval 과 cascade 옵션은 모두 제거해놨습니다..
후.. 삽질을 너무 많이했네요.

### 3. S3 업로드 설정
우테코 계정의 S3는 우테코 계정에서 생성한 EC2에서만 파일을 업로드를 햘 수 있대요. 
개인 테스트용 EC2 인스턴스에서 우테코 S3에서 업로드, 수정, 삭제 테스트까지 완료했습니다.

## 기타
S3 설정 부분을 문서화 하려고 했는데 구글링 하면 다 나오는 내용이고 비중이 거의 없습니다.
오히려 Java 코드 부분과 yml 설정파일이 중요하더라구요. 그래서 문서화는 생략하고, 노션에 참고한 자료 링크 남겨둘게요.

이 PR이 merge되면 local에서의 Spring Boot 구동 시간이 처음에 엄청 길어지고 WARN 로그가 남겨질 거예요.
EC2 Metadata 관련 초기 작동 로그인데, 우리가 로컬에서 인텔리제이를 통해 서버를 띄울 때 주는 VM 옵션을
```
-Dspring.config.location=classpath:/application.yml,file:./cvi-backend-secret/application-jwt.yml,file:./cvi-backend-secret/application-client-secret.yml,file:./cvi-backend-secret/application-publicdata-secret.yml,file:./cvi-backend-secret/application-aws-s3.yml -Dcom.amazonaws.sdk.disableEc2Metadata=true
```
이렇게, 마지막에 `-Dcom.amazonaws.sdk.disableEc2Metadata=true` 만 추가하면 됩니다.
그래도 로그는 뜨긴 뜨지만, 관련 작업을 안하게 돼서 속도가 조금 증가한다고 하네요.

로컬에서는 무시하면 되는 로그고, EC2에서 구동할 때는 이 로그가 안 뜨고 다른 WARN 로그가 뜨는데, 무시하셔도 됩니다.

이상입니다!!

2021-09-07 01:09 UTC, YounghoonKwon commented on backend/src/main/java/com/backjoongwon/cvi/DataLoader.java
> +@Profile("dev")
dev 환경 분리 확-인

2021-09-07 01:10 UTC, YounghoonKwon commented on backend/src/main/java/com/backjoongwon/cvi/aws/s3/AwsS3Uploader.java
> +import com.amazonaws.services.s3.model.PutObjectRequest;
ㄷ ㄷ

2021-09-07 01:11 UTC, YounghoonKwon commented on backend/src/main/java/com/backjoongwon/cvi/aws/s3/AwsS3Uploader.java
> +            log.debug("S3의 {} 파일 삭제 실패", s3DirPath + fileName);
로깅 👍

2021-09-07 01:11 UTC, YounghoonKwon commented on backend/src/main/java/com/backjoongwon/cvi/aws/s3/AwsS3Uploader.java
> +}
개 투더 행

2021-09-07 01:12 UTC, YounghoonKwon commented on backend/src/main/java/com/backjoongwon/cvi/image/ImageType.java
> +    SVG("svg");
gif 같은거도 가능하려나요,,? 그냥 궁금쓰,,

2021-09-07 01:13 UTC, YounghoonKwon commented on backend/src/main/java/com/backjoongwon/cvi/image/ImageType.java
> +    ImageType(String fileNameExtension) {
fileExtensionName은 어떤가요?

2021-09-07 01:13 UTC, YounghoonKwon commented on backend/src/main/java/com/backjoongwon/cvi/image/ImageType.java
> +}
개-행?

2021-09-07 01:21 UTC, YounghoonKwon approved these changes
first of all, I appreciate for all your effort on this feature.
you did a great job and keep it work
i guess you got some white hairs caz of this
great job👍

2021-09-07 09:04 UTC, taehee-kim-dev commented on backend/src/main/java/com/backjoongwon/cvi/DataLoader.java
> +@Profile("dev")
> dev 환경 분리 확-인

저거 로컬에서 잠깐 바꾼건데 원상복구를 안해놨네..
수정해서 푸시했음!!

2021-09-08 04:33 UTC, Livenow14 requested changes
고생하셨습니다 :)

2021-09-08 04:33 UTC, Livenow14 commented on backend/src/main/java/com/backjoongwon/cvi/post/service/PostService.java
> +
yml에다 적용한 다음 @Value로 받아도 좋을듯요!

2021-09-08 04:33 UTC, Livenow14 commented on backend/src/main/resources/application.yml
>      org.hibernate.SQL: debug
yml에 적용을 하면, xml파일이 무시가 될 수 있어요!! 
xm파일을 자성한 이상, xml에서 로깅 레벨을 관리하는 게 좋을 거같아요!

2021-09-08 04:33 UTC, Livenow14 commented on backend/src/main/resources/application.yml
>      org.hibernate.SQL: debug
https://livenow14.tistory.com/64 의 Log 설정 참조 순서부분 확인해주세요!  (블로그 자랑 맞습니다 ㅎㅎㅎㅎ)

2021-09-08 04:33 UTC, Livenow14 commented on backend/src/test/java/com/backjoongwon/cvi/post/controller/PreprocessPostControllerTest.java
> +    protected static final String IMAGE4_S3_URL = "{이미지4 S3 URL}";
따로 factory를 만들어 관리해보는 것은 어떨까요?

2021-09-08 04:48 UTC, thisisyoungbin approved these changes
수고하셨습니다!! :)
로컬이랑 프로덕션 환경에서 다른 설정부분 때문에 고생 좀 하셨겠네요.
테스트 부분도 각각 다른 환경으로 작성하느라 고생하셨습니다
수고하셨어요 !

2021-09-08 04:53 UTC, taehee-kim-dev commented on backend/src/main/java/com/backjoongwon/cvi/image/ImageType.java
> +    SVG("svg");
고려 안해봤어용 ㅠ

2021-09-08 04:54 UTC, taehee-kim-dev commented on backend/src/main/java/com/backjoongwon/cvi/image/ImageType.java
> +}
되어있는데.. 흠.. 저 17번 째 줄에 빨간색 마이너스 표시가 있어야 개행이 안 된걸로 알고 있습니다!!

2021-09-08 04:54 UTC, taehee-kim-dev commented on backend/src/main/java/com/backjoongwon/cvi/aws/s3/AwsS3Uploader.java
> +}
되어있는데.. 흠.. 저 17번 째 줄에 빨간색 마이너스 표시가 있어야 개행이 안 된걸로 알고 있습니다!!

2021-09-08 04:56 UTC, taehee-kim-dev commented on backend/src/main/java/com/backjoongwon/cvi/image/ImageType.java
> +    ImageType(String fileNameExtension) {
저도 이것때문에 좀 찾아봤는데,
- https://en.wikipedia.org/wiki/Filename_extension
- https://support.microsoft.com/en-us/windows/common-file-name-extensions-in-windows-da4a4430-8e76-89c5-59f7-1cdbbc75cb01

영어권에서 다 file name extension으로 쓰더라구요!!
그래서 저렇게 네이밍을 했습니다!!

2021-09-08 04:57 UTC, taehee-kim-dev commented on backend/src/main/java/com/backjoongwon/cvi/aws/s3/AwsS3Uploader.java
> +
흠.. 자동 포맷팅으로도 안 잡히는군요.
원래 import와 최상위 코드 작성 부분 사이 공백이 한 줄이 컨벤션인가요!!??

일단 반영했습니다!!

2021-09-08 04:58 UTC, taehee-kim-dev commented on backend/src/main/java/com/backjoongwon/cvi/image/ImageType.java
> +    SVG("svg");
name.lowercase()로 해결하자는 말씀이신거죠!?!?

2021-09-08 04:59 UTC, taehee-kim-dev commented on backend/src/main/java/com/backjoongwon/cvi/image/domain/Image.java
> +    }
맞아요... 이것 때문에 버그를 만났죠.. ㅎㅎ
인자에서 Post를 삭제할게요!!

2021-09-08 05:03 UTC, taehee-kim-dev commented on backend/src/main/java/com/backjoongwon/cvi/post/domain/Images.java
> +    }
다시 보니 테스트에서만 쿼리 확인용으로 쓰는 함수네요... 허허..
바로 삭제했습니다!!

2021-09-08 05:14 UTC, taehee-kim-dev commented on backend/src/main/resources/application.yml
>      org.hibernate.SQL: debug
프로덕션 코드 패키지의 로깅 레벨만 debug로 잡고 싶었어요.
전체를 debug레벨로 두면 너무 많은 로그가 뜨더라구요.
일단 반영했습니다!

2021-09-08 06:23 UTC, taehee-kim-dev commented on backend/src/test/java/com/backjoongwon/cvi/post/controller/PreprocessPostControllerTest.java
> +    protected static final String IMAGE4_S3_URL = "{이미지4 S3 URL}";
추후에 리팩토링시에 적용해 볼게요!!!

2021-09-08 06:40 UTC, merged