[FE] 홈페이지 콘텐츠 수정
woowacourse-teams/2021-cvi pull request #260
Opened 2021-09-10 20:13 UTC by jum0

#259

2021-09-10 20:13 UTC, Livenow14 commented
Can one of the admins verify this patch?

2021-09-11 15:25 UTC, HyuuunjuKim requested changes
저번에 논의했을 때는 부작용보다 증상의 내용들을 넣기로 했던것 같은데, `sideEffect`라는 네이밍과 `symptom`이라는 네이밍이 섞여 있는 것 같네요! `symptom`으로 통일하는건 어떨까요?🧐

`VaccinationSideEffectChart.js`컴포넌트의 재사용성에 대해 아쉬움이 조금 남아요! 수평 막대 그래프의 경우에는 이번에 재사용성 있게 만들면, 나중에도 잘 쓸 수 있지 않을까해서요!
우리 도메인 성격의 네이밍보다는 조금 더 일반적인 네이밍을 사용해보는건 어떨까요? ㅎ ㅎ

수고하셨습니다ㅎ ㅎ 코멘트 확인 부탁드려요~!

2021-09-11 15:25 UTC, HyuuunjuKim commented on frontend/src/components/HomeContent/HomeContent.js
> +const sideEffectsData = [
`symptomList`처럼 `sideEffects`라는 단어 대신 `symptom`을 사용하는 건 어떨까요? 안에 내용물은 `symptom`인거 같아서요!

2021-09-11 15:25 UTC, HyuuunjuKim commented on frontend/src/components/VaccinationSideEffectChart/VaccinationSideEffectChart.styles.js
> +  & > *:nth-of-type(1) > :nth-of-type(2) {
VaccinationSideEffectChart.js에서 props로 색을 건네주어 `background-color`를 지정하는 방식은 어떠신가요?

2021-09-11 15:25 UTC, HyuuunjuKim commented on frontend/src/components/VaccinationSideEffectChart/VaccinationSideEffectChart.js
> +const VaccinationSideEffectChart = ({ sideEffects }) => (
네이밍이 아쉬운 것 같아요! 지금처럼 도메인의 성격을 넣기보다는`HorizontalBarChart`처럼 일반적인 이름은 어떨까요? 받는 props도 sideEffects가 아니라 data? dataList? 같은 일반적인 이름을 사용해서 전체적으로 이 컴포넌트를 재사용성가능하게 만들고 `common/` 폴더 하위로 넣는 방법에 대해 어떻게 생각하시나요?

2021-09-11 15:28 UTC, HyuuunjuKim commented on frontend/src/components/VaccinationSideEffectChart/VaccinationSideEffectChart.styles.js
> +  & > *:nth-of-type(1) > :nth-of-type(2) {
흠 근데 또 생각해보니 바깥에서 어떻게 props로 전달해줄수 있을지 고민이 되네요! 지금 방식이 좋은 것 같기도 하고 🤔🤔🤔 주모 생각은 어떠신가요?

2021-09-11 15:31 UTC, HyuuunjuKim requested changes

2021-09-11 15:31 UTC, HyuuunjuKim commented on frontend/src/components/VaccinationSideEffectChart/VaccinationSideEffectChart.js
> +      <SideEffectContainer key={index} index={index}>
`index={index}` 이 부분은 왜 스타일드 컴포넌트로 넘기는걸까요?

2021-09-11 15:31 UTC, HyuuunjuKim commented on frontend/src/components/VaccinationSideEffectChart/VaccinationSideEffectChart.js
> +      <SideEffectContainer key={index} index={index}>
`key={index}`보다 더 나은 방법으로 key를 줄 수 없을까요?

2021-09-12 16:43 UTC, jum0 commented on frontend/src/components/HomeContent/HomeContent.js
> +const sideEffectsData = [
좋아요! 처음에 `symptom`으로 했다가, `증상이 결국 부작용 아닌가` 이런 식으로 생각해서 저 스스로도 혼용해서 사용했던 것 같기도 하네요ㅠ 모두 `symptom` 관련 용어로 통일할게요!

2021-09-12 17:26 UTC, jum0 commented on frontend/src/components/VaccinationSideEffectChart/VaccinationSideEffectChart.styles.js
> +  & > *:nth-of-type(1) > :nth-of-type(2) {
다시 생각해보니까 색을 컴포넌트 스타일 파일에서 지정해주는 것보다 props로 넘기는 게 더 나을 것 같아요! 넘기는 방식은 `symptomList`에 `color` property를 만들어서 넘기면 될 것 같아요! 이렇게 수정해볼게요!

2021-09-12 17:44 UTC, jum0 commented on frontend/src/components/VaccinationSideEffectChart/VaccinationSideEffectChart.styles.js
> +  & > *:nth-of-type(1) > :nth-of-type(2) {
그런데, 또 다시 생각해보니깐 `symptomList` 증상리스트라는 데이터에 property로 증상의 이름, 증상의 퍼센트는 이해가 되는데, 색이 들어있는 게 조금 어색하긴 한 것 같기도 하네요. `color`는 더 어색한 것 같아서 일단 `barColor`로 만들었는데, 다시 이야기 해보면 좋을 것 같아요!

2021-09-12 17:46 UTC, jum0 commented on frontend/src/components/VaccinationSideEffectChart/VaccinationSideEffectChart.js
> +const VaccinationSideEffectChart = ({ sideEffects }) => (
더 일반적인 이름으로 하는 게 좋겠어요! 좋습니당

2021-09-12 18:04 UTC, jum0 commented on frontend/src/components/VaccinationSideEffectChart/VaccinationSideEffectChart.js
> +      <SideEffectContainer key={index} index={index}>
`index`는 스타일 파일의 `Bar`에서 쓰이는데, 각각의 막대 애니메이션이 시작하는 시점을 다르게 하려고 사용했습니다!

2021-09-12 18:07 UTC, jum0 commented on frontend/src/components/VaccinationSideEffectChart/VaccinationSideEffectChart.js
> +      <SideEffectContainer key={index} index={index}>
React에서 key로 index 사용하는 것을 지양하는데, 그런 경우는 나열되는 요소가 추가 또는 삭제되는 경우에만 해당된다고 알고 있어요. 현재 컴포넌트에서 막대의 개수가 동적으로 변하는 게 아닌 그대로 보여주기만 하는 경우라서 key로 index를 부여하는 게 충분하다는 생각이 듭니다!

2021-09-13 12:56 UTC, HyuuunjuKim commented on frontend/src/components/VaccinationSideEffectChart/VaccinationSideEffectChart.styles.js
> +  & > *:nth-of-type(1) > :nth-of-type(2) {
저도 이 부분 때문에 두 번째 코멘트를 남긴것 같아요!
뭔가 데이터에 color를 넣기보다는,,,, BarChart 컴포넌트가 스스로 색에 대한 변수를 갖고 있는건 어떨까 싶네요! 근데 이렇게 하면 결국 스타일 파일에서 주는거랑 별반 다르지 않은 것 같기도 해서 고민되네여 🤨

2021-09-13 12:58 UTC, HyuuunjuKim commented on frontend/src/components/VaccinationSideEffectChart/VaccinationSideEffectChart.js
> +      <SideEffectContainer key={index} index={index}>
스타일드 컴포넌트인 SideEffectConatainer에서는 index를 사용 안하지 않나요? 🤔🤔🤔

2021-09-13 13:00 UTC, HyuuunjuKim commented on frontend/src/components/VaccinationSideEffectChart/VaccinationSideEffectChart.js
> +      <SideEffectContainer key={index} index={index}>
symptom의 name으로 key를 주면, index 사용을 지양하면서도 key값을 unique하게 가져갈수 있지 않을까요? 🤔🤔🤔

2021-09-14 07:37 UTC, jum0 commented on frontend/src/components/VaccinationSideEffectChart/VaccinationSideEffectChart.js
> +      <SideEffectContainer key={index} index={index}>
아아 스타일드 컴포넌트 `<SideEffectContainer>`에서는 사용하고 있지 않네요! 수정할게요!

2021-09-14 07:48 UTC, jum0 commented on frontend/src/components/VaccinationSideEffectChart/VaccinationSideEffectChart.js
> +      <SideEffectContainer key={index} index={index}>
리액트에서 key를 판단할 때, key로 name이 있든지, index로 있든지 형제 요소간의 추가 삭제가 없기 때문에 둘다 unique하다고 생각돼요! 다만, 공식 문서에서 참조하고 있는 [글](https://robinpokorny.medium.com/index-as-a-key-is-an-anti-pattern-e0349aece318)을 보니, 
![image](https://user-images.githubusercontent.com/40762111/133217032-84a302d1-4038-4b72-b2dc-381b2bb3622c.png)
두 번째 조건을 생각해봤을 때 name으로 수정하는 게 좀 더 안전하게 키를 사용하는 방향이라고 느껴지네요! name으로 변경하겠습니다! 감사합니다!

2021-09-14 07:55 UTC, jum0 commented on frontend/src/components/VaccinationSideEffectChart/VaccinationSideEffectChart.styles.js
> +  & > *:nth-of-type(1) > :nth-of-type(2) {
데이터에 color를 넣으면 어색한 부분이 있다는 단점이 있지만, 컴포넌트와 컴포넌트 스타일을 수정하지 않는 이점이 있다는 생각이 들긴 해요! 그래서 데이터에 넣어도 되지 않을까란 생각이 듭니다!

2021-09-14 09:21 UTC, HyuuunjuKim commented
수고하셨습니다 ㅎㅎ

2021-09-14 09:21 UTC, HyuuunjuKim commented
수고하셨습니다 ㅎㅎ

2021-09-14 09:21 UTC, merged