[BE] social login test 작성(#43)
woowacourse-teams/2021-cvi pull request #58
Opened 2021-07-26 04:59 UTC by thisisyoungbin

2021-07-26 05:58 UTC, Livenow14 requested changes
피드백 반영 부탁드립니다!

2021-07-26 05:58 UTC, Livenow14 commented on backend/src/main/java/com/backjoongwon/cvi/auth/application/AuthService.java
> +            return UserResponse.newUser(null, null, null, false,
Objects.isEmpty()라는 메서드를 활용해보는게 좋을거같아요 !

2021-07-26 05:58 UTC, Livenow14 commented on backend/src/main/java/com/backjoongwon/cvi/auth/application/AuthService.java
> +            return UserResponse.newUser(null, null, null, false,
if(!Objects.isEmpty(found)){
User user = foundUser.get();
        String token = jwtTokenProvider.createToken(user.getId());
        return UserResponse.of(user, token);
}
식으로 비즈니스 흐름을 조금더 나타내주면 좋을거같아요 !

2021-07-26 05:58 UTC, Livenow14 commented on backend/src/main/java/com/backjoongwon/cvi/user/dto/UserResponse.java
> +    }
아까 말했던 부분! 
정적 팩토리 메서드의 의믜를 더해주기

2021-07-26 05:58 UTC, Livenow14 commented on backend/src/main/resources/application.yml
> +      client-secret: R_zN6l1A3V
이부분도 아까 말했떤 부분! 
Secret키는 따로 분리해서 사용하기로 해요!

2021-07-26 05:58 UTC, Livenow14 commented on backend/src/test/java/com/backjoongwon/cvi/auth/domain/authorization/AuthorizationManagerTest.java
> +}
개행으로 끝내주세요!!

2021-07-26 05:58 UTC, Livenow14 commented on backend/src/test/java/com/backjoongwon/cvi/auth/domain/authorization/KakaoAuthorizationTest.java
> +}
개행!

2021-07-26 05:58 UTC, Livenow14 commented on backend/src/test/java/com/backjoongwon/cvi/auth/domain/authorization/NaverAuthorizationTest.java
> +}
개행

2021-07-26 06:23 UTC, taehee-kim-dev approved these changes
👍

2021-07-27 01:16 UTC, YounghoonKwon commented on backend/src/main/java/com/backjoongwon/cvi/auth/domain/authorization/KakaoAuthorization.java
> +            throw new MappingFailureException("토큰 정보를 불러오는 데 실패했습니다.");
MappingFailure이랑 메세지랑 의미가 잘 맞지 않는 것 같아요.

2021-07-27 01:18 UTC, YounghoonKwon commented on backend/src/main/java/com/backjoongwon/cvi/user/dto/UserResponse.java
> +                null, socialProvider, socialId, socialProfileUrl);
일전에 말씀드렸어요.

2021-07-27 01:19 UTC, YounghoonKwon commented on backend/src/test/java/com/backjoongwon/cvi/auth/application/AuthServiceTest.java
> +        willReturn(Optional.of(user)).given(userRepository).findBySocialProviderAndSocialId(SocialProvider.NAVER, "NAVER_ID");
상수화 해주세요.

2021-07-27 01:21 UTC, YounghoonKwon commented on backend/src/test/java/com/backjoongwon/cvi/auth/domain/authorization/KakaoAuthorizationTest.java
> +class KakaoAuthorizationTest {
다른 테스트에도 상수화를 하기러 했으면 다 통일해주세요.

2021-07-27 01:22 UTC, YounghoonKwon commented on backend/src/test/java/com/backjoongwon/cvi/auth/domain/authorization/KakaoAuthorizationTest.java
> +        assertThatThrownBy(() -> kakaoAuthorization.mapToProfile(ResponseEntity.ok("NOT_VALID_PROFILE")))
`ResponseEntity.ok("NOT_VALID_PROFILE") `
이부분도 다른 테스트에서는 상수화했더군요.

2021-07-27 01:23 UTC, YounghoonKwon commented on backend/src/test/java/com/backjoongwon/cvi/post/application/PostServiceTest.java
> +@SpringBootTest
Annotation 선언 순서도 다른 테스트와 맞춰주세요.

2021-07-27 01:24 UTC, YounghoonKwon reviewed
전반적으로 깔끔해요

2021-07-27 01:43 UTC, thisisyoungbin commented on backend/src/test/java/com/backjoongwon/cvi/auth/domain/authorization/KakaoAuthorizationTest.java
> +        assertThatThrownBy(() -> kakaoAuthorization.mapToProfile(ResponseEntity.ok("NOT_VALID_PROFILE")))
변경되어 예외가 발생하는 부분은 따로 상수화하지 않았습니다

2021-07-27 01:49 UTC, merged